# inspired on
# https://github.com/mitmproxy/pdoc/blob/main/.github/workflows/docs.yml
---
name: build API reference documentation

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install pdocs
        run: pip install pdoc

      - run: pdoc -o pdocs --docformat google ./prototype_python_library

      - uses: actions/upload-pages-artifact@v1
        with:
          path: pdocs/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v1
